### ISSUE TITLE
TYWE1S supportet too?

### ISSUE THREAD

**Issue by MasterOfPuppets111** [andreondra/homeassistant-poolstar-poolex#1]
Hello Andreondra,

Thank you very much for sharing this project!

I have a poolex pool heat pump too, but in my display there is a TYWE1S chip, not a WBR3 😞

Does this replacement work with my chip?

![Image](https://github.com/user-attachments/assets/add126ca-8b69-48cc-b0ca-7cb110c2b8ee)

Best regards and thank you
Pierre

**Comment by andreondra** [comment]
Hello,

the type of Tuya chip present in the controller should not matter as long as communication with the controller's processor is based on the Tuya protocol. We effectively replace the Tuya chip with ESP in my guide.

I had a quick look at the [documentation](https://developer.tuya.com/en/docs/iot/wifie1smodulemcu?id=K9hhi0xp301u1) and apparently this chip is based on the ESP8266. 

This can be good news, because probably you won't need to install another ESP board, you can try to flash the TYWE1S directly. Just have a look at the pinout in the documentation. Probably it can be flashed like every other ESP8266EX based board.

I found [this guide](https://github.com/jazzmonger/wood-pellet-stove-with-TYWE1S-Tuya-chip) which may be helpful for you: here they flash the TYWE1S directly with esphome firmware.

If it doesn't work, you can proceed with my guide and install another ESP flashed with the esphome firmware.

Good luck!

**Comment by MasterOfPuppets111** [comment]
Works like a charm 😊🙌

I soldered VCC, GND, TX and RX from the TYWE1S to my SerialUSB converter and Flash ESPHome.

![Image](https://github.com/user-attachments/assets/5eacc5d2-6f2c-4f0c-b345-353916c4ef28)

Im only unshure with gpio for tx and rx in the defines from esp home.... if i see it right, the TYWE1S uses U1TX and U1RX to speak with the maincontroller... that schuld be GPIO1 and 3 i think....

I wonder if you can elicit more information (flow etc.) sensors for this are available.

**Comment by andreondra** [comment]
Glad you got it flashed.

As for the GPIO mapping, you are probably right. You can try swapping those if it does not work.

I don't think there are more information that can be read from the Tuya interface than those already available in the Tuya app. If you need to read more information including service data, skip the controller completely and communicate with the heat pump using the project I linked in the readme (method 1).

**Comment by Arnaud-DEFAY** [comment]
Hello,

A big thank you to @andreondra and @MasterOfPuppets111! Thanks to your contributions, I was able to connect my Poolex heat pump without using Tuya.

For anyone interested, here is the YAML configuration to use for a TYWE1S chip to get everything working properly:

```
substitutions:
  device_id: "pool_heat_pump"

esphome:
  name: eh_${device_id}
  friendly_name: pool_heat_pump

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EDIT_ME"

ota:
  - platform: esphome
    password: "EDIT_ME"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "EDIT_ME"
    password: "EDIT_ME"

captive_portal:

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

tuya:

# On-off.
switch:
  - platform: "tuya"
    name: ${device_id}_power
    switch_datapoint: 1

# Target temperature.
number:
  - platform: "tuya"
    name: ${device_id}_target_temp
    device_class: temperature
    unit_of_measurement: "°C"
    number_datapoint: 2
    min_value: 20
    max_value: 40
    step: 1

# Current temperature.
sensor:
  - platform: "tuya"
    name: ${device_id}_current_temp
    device_class: temperature
    unit_of_measurement: "°C"
    sensor_datapoint: 3

# Current mode.
select:
  - platform: "tuya"
    name: ${device_id}_mode
    enum_datapoint: 4
    optimistic: false
    options:
      0: "ECO Heat"
      1: "ECO Cool"
      2: "Automatic"
      3: "Boost Heat"
      4: "Silent Heat"
      5: "Boost Cool"
      6: "Silent Cool"
    
```
